<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BlockInformationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $blockInformation = [
            [
                'name' => 'Building Age',
                'description' => 'Age of the building in years',
                'category' => 'Building Details',
                'data_type' => 'number',
                'validation_rules' => '{"min": 0, "max": 200}',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 1,
                'default_value' => null,
                'options' => null,
                'help_text' => 'Enter the age of the building in years',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Construction Material',
                'description' => 'Primary construction material used',
                'category' => 'Building Details',
                'data_type' => 'select',
                'validation_rules' => '{"required": true}',
                'is_required' => true,
                'is_active' => true,
                'sort_order' => 2,
                'default_value' => null,
                'options' => json_encode(['Concrete', 'Steel', 'Wood', 'Brick', 'Stone', 'Mixed']),
                'help_text' => 'Select the primary construction material',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Roof Type',
                'description' => 'Type of roof structure',
                'category' => 'Building Details',
                'data_type' => 'select',
                'validation_rules' => '{"required": false}',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 3,
                'default_value' => null,
                'options' => json_encode(['Flat', 'Pitched', 'Gable', 'Hip', 'Mansard', 'Gambrel']),
                'help_text' => 'Select the roof type',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Heating System',
                'description' => 'Type of heating system installed',
                'category' => 'Utilities',
                'data_type' => 'select',
                'validation_rules' => '{"required": false}',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 4,
                'default_value' => null,
                'options' => json_encode(['Central Heating', 'Individual Units', 'Heat Pump', 'Radiant', 'None']),
                'help_text' => 'Select the heating system type',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Cooling System',
                'description' => 'Type of cooling system installed',
                'category' => 'Utilities',
                'data_type' => 'select',
                'validation_rules' => '{"required": false}',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 5,
                'default_value' => null,
                'options' => json_encode(['Central AC', 'Individual Units', 'Heat Pump', 'Evaporative', 'None']),
                'help_text' => 'Select the cooling system type',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Parking Type',
                'description' => 'Type of parking available',
                'category' => 'Parking',
                'data_type' => 'select',
                'validation_rules' => '{"required": false}',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 6,
                'default_value' => null,
                'options' => json_encode(['Surface', 'Underground', 'Multi-level', 'Street', 'None']),
                'help_text' => 'Select the parking type',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Security Features',
                'description' => 'Security features available',
                'category' => 'Security',
                'data_type' => 'multiselect',
                'validation_rules' => '{"required": false}',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 7,
                'default_value' => null,
                'options' => json_encode(['CCTV', 'Access Control', 'Security Guard', 'Alarm System', 'Intercom', 'None']),
                'help_text' => 'Select all applicable security features',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Amenities',
                'description' => 'Available amenities in the block',
                'category' => 'Amenities',
                'data_type' => 'multiselect',
                'validation_rules' => '{"required": false}',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 8,
                'default_value' => null,
                'options' => json_encode(['Gym', 'Pool', 'Garden', 'Playground', 'BBQ Area', 'Community Hall', 'None']),
                'help_text' => 'Select all available amenities',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Maintenance Schedule',
                'description' => 'Regular maintenance schedule',
                'category' => 'Maintenance',
                'data_type' => 'select',
                'validation_rules' => '{"required": false}',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 9,
                'default_value' => null,
                'options' => json_encode(['Weekly', 'Monthly', 'Quarterly', 'Bi-annually', 'Annually', 'As Needed']),
                'help_text' => 'Select the maintenance schedule frequency',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Insurance Expiry',
                'description' => 'Insurance expiry date',
                'category' => 'Legal',
                'data_type' => 'date',
                'validation_rules' => '{"required": true, "min_date": "today"}',
                'is_required' => true,
                'is_active' => true,
                'sort_order' => 10,
                'default_value' => null,
                'options' => null,
                'help_text' => 'Enter the insurance expiry date',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Fire Safety Rating',
                'description' => 'Fire safety rating of the building',
                'category' => 'Safety',
                'data_type' => 'select',
                'validation_rules' => '{"required": true}',
                'is_required' => true,
                'is_active' => true,
                'sort_order' => 11,
                'default_value' => null,
                'options' => json_encode(['A', 'B', 'C', 'D', 'E', 'F']),
                'help_text' => 'Select the fire safety rating',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Energy Rating',
                'description' => 'Energy efficiency rating',
                'category' => 'Environmental',
                'data_type' => 'select',
                'validation_rules' => '{"required": false}',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 12,
                'default_value' => null,
                'options' => json_encode(['A+', 'A', 'B', 'C', 'D', 'E', 'F', 'G']),
                'help_text' => 'Select the energy efficiency rating',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Last Renovation',
                'description' => 'Date of last major renovation',
                'category' => 'Building Details',
                'data_type' => 'date',
                'validation_rules' => '{"required": false, "max_date": "today"}',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 13,
                'default_value' => null,
                'options' => null,
                'help_text' => 'Enter the date of last major renovation',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Building Condition',
                'description' => 'Overall condition of the building',
                'category' => 'Building Details',
                'data_type' => 'select',
                'validation_rules' => '{"required": true}',
                'is_required' => true,
                'is_active' => true,
                'sort_order' => 14,
                'default_value' => null,
                'options' => json_encode(['Excellent', 'Good', 'Fair', 'Poor', 'Critical']),
                'help_text' => 'Select the overall building condition',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Accessibility Features',
                'description' => 'Accessibility features available',
                'category' => 'Accessibility',
                'data_type' => 'multiselect',
                'validation_rules' => '{"required": false}',
                'is_required' => false,
                'is_active' => true,
                'sort_order' => 15,
                'default_value' => null,
                'options' => json_encode(['Ramp Access', 'Elevator', 'Wide Doors', 'Accessible Bathrooms', 'Handrails', 'None']),
                'help_text' => 'Select all available accessibility features',
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];

        foreach ($blockInformation as $info) {
            DB::table('block_information')->insert($info);
        }
    }
};
