<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['country_code' => 'US', 'country_name' => 'United States', 'phonecode' => 1],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'phonecode' => 1],
            ['country_code' => 'GB', 'country_name' => 'United Kingdom', 'phonecode' => 44],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'phonecode' => 61],
            ['country_code' => 'DE', 'country_name' => 'Germany', 'phonecode' => 49],
            ['country_code' => 'FR', 'country_name' => 'France', 'phonecode' => 33],
            ['country_code' => 'IT', 'country_name' => 'Italy', 'phonecode' => 39],
            ['country_code' => 'ES', 'country_name' => 'Spain', 'phonecode' => 34],
            ['country_code' => 'NL', 'country_name' => 'Netherlands', 'phonecode' => 31],
            ['country_code' => 'BE', 'country_name' => 'Belgium', 'phonecode' => 32],
            ['country_code' => 'CH', 'country_name' => 'Switzerland', 'phonecode' => 41],
            ['country_code' => 'AT', 'country_name' => 'Austria', 'phonecode' => 43],
            ['country_code' => 'SE', 'country_name' => 'Sweden', 'phonecode' => 46],
            ['country_code' => 'NO', 'country_name' => 'Norway', 'phonecode' => 47],
            ['country_code' => 'DK', 'country_name' => 'Denmark', 'phonecode' => 45],
            ['country_code' => 'FI', 'country_name' => 'Finland', 'phonecode' => 358],
            ['country_code' => 'IE', 'country_name' => 'Ireland', 'phonecode' => 353],
            ['country_code' => 'PT', 'country_name' => 'Portugal', 'phonecode' => 351],
            ['country_code' => 'GR', 'country_name' => 'Greece', 'phonecode' => 30],
            ['country_code' => 'PL', 'country_name' => 'Poland', 'phonecode' => 48],
            ['country_code' => 'CZ', 'country_name' => 'Czech Republic', 'phonecode' => 420],
            ['country_code' => 'HU', 'country_name' => 'Hungary', 'phonecode' => 36],
            ['country_code' => 'RO', 'country_name' => 'Romania', 'phonecode' => 40],
            ['country_code' => 'BG', 'country_name' => 'Bulgaria', 'phonecode' => 359],
            ['country_code' => 'HR', 'country_name' => 'Croatia', 'phonecode' => 385],
            ['country_code' => 'SI', 'country_name' => 'Slovenia', 'phonecode' => 386],
            ['country_code' => 'SK', 'country_name' => 'Slovakia', 'phonecode' => 421],
            ['country_code' => 'LT', 'country_name' => 'Lithuania', 'phonecode' => 370],
            ['country_code' => 'LV', 'country_name' => 'Latvia', 'phonecode' => 371],
            ['country_code' => 'EE', 'country_name' => 'Estonia', 'phonecode' => 372],
            ['country_code' => 'MT', 'country_name' => 'Malta', 'phonecode' => 356],
            ['country_code' => 'CY', 'country_name' => 'Cyprus', 'phonecode' => 357],
            ['country_code' => 'LU', 'country_name' => 'Luxembourg', 'phonecode' => 352],
            ['country_code' => 'IS', 'country_name' => 'Iceland', 'phonecode' => 354],
            ['country_code' => 'LI', 'country_name' => 'Liechtenstein', 'phonecode' => 423],
            ['country_code' => 'MC', 'country_name' => 'Monaco', 'phonecode' => 377],
            ['country_code' => 'SM', 'country_name' => 'San Marino', 'phonecode' => 378],
            ['country_code' => 'VA', 'country_name' => 'Vatican City', 'phonecode' => 379],
            ['country_code' => 'AD', 'country_name' => 'Andorra', 'phonecode' => 376],
            ['country_code' => 'NZ', 'country_name' => 'New Zealand', 'phonecode' => 64],
            ['country_code' => 'JP', 'country_name' => 'Japan', 'phonecode' => 81],
            ['country_code' => 'KR', 'country_name' => 'South Korea', 'phonecode' => 82],
            ['country_code' => 'CN', 'country_name' => 'China', 'phonecode' => 86],
            ['country_code' => 'IN', 'country_name' => 'India', 'phonecode' => 91],
            ['country_code' => 'SG', 'country_name' => 'Singapore', 'phonecode' => 65],
            ['country_code' => 'MY', 'country_name' => 'Malaysia', 'phonecode' => 60],
            ['country_code' => 'TH', 'country_name' => 'Thailand', 'phonecode' => 66],
            ['country_code' => 'VN', 'country_name' => 'Vietnam', 'phonecode' => 84],
            ['country_code' => 'PH', 'country_name' => 'Philippines', 'phonecode' => 63],
            ['country_code' => 'ID', 'country_name' => 'Indonesia', 'phonecode' => 62],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'phonecode' => 55],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'phonecode' => 54],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'phonecode' => 52],
            ['country_code' => 'CL', 'country_name' => 'Chile', 'phonecode' => 56],
            ['country_code' => 'CO', 'country_name' => 'Colombia', 'phonecode' => 57],
            ['country_code' => 'PE', 'country_name' => 'Peru', 'phonecode' => 51],
            ['country_code' => 'VE', 'country_name' => 'Venezuela', 'phonecode' => 58],
            ['country_code' => 'EC', 'country_name' => 'Ecuador', 'phonecode' => 593],
            ['country_code' => 'BO', 'country_name' => 'Bolivia', 'phonecode' => 591],
            ['country_code' => 'PY', 'country_name' => 'Paraguay', 'phonecode' => 595],
            ['country_code' => 'UY', 'country_name' => 'Uruguay', 'phonecode' => 598],
            ['country_code' => 'GY', 'country_name' => 'Guyana', 'phonecode' => 592],
            ['country_code' => 'SR', 'country_name' => 'Suriname', 'phonecode' => 597],
            ['country_code' => 'FK', 'country_name' => 'Falkland Islands', 'phonecode' => 500],
            ['country_code' => 'ZA', 'country_name' => 'South Africa', 'phonecode' => 27],
            ['country_code' => 'EG', 'country_name' => 'Egypt', 'phonecode' => 20],
            ['country_code' => 'NG', 'country_name' => 'Nigeria', 'phonecode' => 234],
            ['country_code' => 'KE', 'country_name' => 'Kenya', 'phonecode' => 254],
            ['country_code' => 'GH', 'country_name' => 'Ghana', 'phonecode' => 233],
            ['country_code' => 'ET', 'country_name' => 'Ethiopia', 'phonecode' => 251],
            ['country_code' => 'TZ', 'country_name' => 'Tanzania', 'phonecode' => 255],
            ['country_code' => 'UG', 'country_name' => 'Uganda', 'phonecode' => 256],
            ['country_code' => 'DZ', 'country_name' => 'Algeria', 'phonecode' => 213],
            ['country_code' => 'MA', 'country_name' => 'Morocco', 'phonecode' => 212],
            ['country_code' => 'TN', 'country_name' => 'Tunisia', 'phonecode' => 216],
            ['country_code' => 'LY', 'country_name' => 'Libya', 'phonecode' => 218],
            ['country_code' => 'SD', 'country_name' => 'Sudan', 'phonecode' => 249],
            ['country_code' => 'CM', 'country_name' => 'Cameroon', 'phonecode' => 237],
            ['country_code' => 'CI', 'country_name' => 'Ivory Coast', 'phonecode' => 225],
            ['country_code' => 'SN', 'country_name' => 'Senegal', 'phonecode' => 221],
            ['country_code' => 'ML', 'country_name' => 'Mali', 'phonecode' => 223],
            ['country_code' => 'BF', 'country_name' => 'Burkina Faso', 'phonecode' => 226],
            ['country_code' => 'NE', 'country_name' => 'Niger', 'phonecode' => 227],
            ['country_code' => 'TD', 'country_name' => 'Chad', 'phonecode' => 235],
            ['country_code' => 'CF', 'country_name' => 'Central African Republic', 'phonecode' => 236],
            ['country_code' => 'CG', 'country_name' => 'Republic of the Congo', 'phonecode' => 242],
            ['country_code' => 'CD', 'country_name' => 'Democratic Republic of the Congo', 'phonecode' => 243],
            ['country_code' => 'GA', 'country_name' => 'Gabon', 'phonecode' => 241],
            ['country_code' => 'GQ', 'country_name' => 'Equatorial Guinea', 'phonecode' => 240],
            ['country_code' => 'ST', 'country_name' => 'Sao Tome and Principe', 'phonecode' => 239],
            ['country_code' => 'AO', 'country_name' => 'Angola', 'phonecode' => 244],
            ['country_code' => 'ZM', 'country_name' => 'Zambia', 'phonecode' => 260],
            ['country_code' => 'ZW', 'country_name' => 'Zimbabwe', 'phonecode' => 263],
            ['country_code' => 'BW', 'country_name' => 'Botswana', 'phonecode' => 267],
            ['country_code' => 'NA', 'country_name' => 'Namibia', 'phonecode' => 264],
            ['country_code' => 'SZ', 'country_name' => 'Eswatini', 'phonecode' => 268],
            ['country_code' => 'LS', 'country_name' => 'Lesotho', 'phonecode' => 266],
            ['country_code' => 'MG', 'country_name' => 'Madagascar', 'phonecode' => 261],
            ['country_code' => 'MU', 'country_name' => 'Mauritius', 'phonecode' => 230],
            ['country_code' => 'SC', 'country_name' => 'Seychelles', 'phonecode' => 248],
            ['country_code' => 'KM', 'country_name' => 'Comoros', 'phonecode' => 269],
            ['country_code' => 'DJ', 'country_name' => 'Djibouti', 'phonecode' => 253],
            ['country_code' => 'SO', 'country_name' => 'Somalia', 'phonecode' => 252],
            ['country_code' => 'ER', 'country_name' => 'Eritrea', 'phonecode' => 291],
            ['country_code' => 'SS', 'country_name' => 'South Sudan', 'phonecode' => 211],
            ['country_code' => 'RW', 'country_name' => 'Rwanda', 'phonecode' => 250],
            ['country_code' => 'BI', 'country_name' => 'Burundi', 'phonecode' => 257],
            ['country_code' => 'MW', 'country_name' => 'Malawi', 'phonecode' => 265],
            ['country_code' => 'MZ', 'country_name' => 'Mozambique', 'phonecode' => 258],
            ['country_code' => 'ZW', 'country_name' => 'Zimbabwe', 'phonecode' => 263],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }

        $this->command->info('Country seeder completed successfully. Created ' . count($countries) . ' countries.');
    }
}
