<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RealBlockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing blocks data (delete instead of truncate to avoid FK constraints)
        DB::table('blocks')->delete();

        $blocks = [
            [
                'id' => 1,
                'name' => 'Fairgreen',
                'management_company' => 'Piazza Square Management Company',
                'block_type_id' => 3,
                'user_id' => 9,
                'address1' => 'Mallow',
                'address2' => 'Cork',
                'address3' => null,
                'image_path' => 'uploads/apm/block/photos/2022/12/',
                'image_name' => '1672497887.7-westside-fairgreen-mallow-co-cork-85115b71_4bb8a742_e90b52db_4fc4a072.jpg',
                'country_id' => 105,
                'state_id' => 1753,
                'car_spaces' => 61,
                'inspection_count' => 24,
                'no_of_units' => 61,
                'created_by' => 4,
                'updated_by' => 4,
                'created_at' => '2022-12-31 14:44:47',
                'updated_at' => '2022-12-31 14:44:47',
            ],
            [
                'id' => 2,
                'name' => '2 George\'s Quay',
                'management_company' => 'Rubylane Management Ltd',
                'block_type_id' => 2,
                'user_id' => 4,
                'address1' => 'George\'s Quay',
                'address2' => 'Cork',
                'address3' => null,
                'image_path' => 'uploads/apm/block/photos/2023/03/',
                'image_name' => '1679657119.Georges Quay.png',
                'country_id' => 105,
                'state_id' => 1753,
                'car_spaces' => 6,
                'inspection_count' => 12,
                'no_of_units' => 4,
                'created_by' => 4,
                'updated_by' => 4,
                'created_at' => '2023-03-24 11:25:19',
                'updated_at' => '2023-03-24 11:25:19',
            ],
            [
                'id' => 3,
                'name' => 'Airways Business Park',
                'management_company' => 'Airways Business & Technology Park Mgt Ltd',
                'block_type_id' => 2,
                'user_id' => 4,
                'address1' => 'Rathmacullig',
                'address2' => 'West Ballygarvan',
                'address3' => 'Co Cork',
                'image_path' => 'uploads/apm/block/photos/2023/03/',
                'image_name' => '1679754053.92_blockpicture_1515474021497.jpeg',
                'country_id' => 105,
                'state_id' => 1753,
                'car_spaces' => 0,
                'inspection_count' => 12,
                'no_of_units' => 12,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2023-03-25 12:00:50',
                'updated_at' => '2023-03-25 14:20:53',
            ],
            [
                'id' => 4,
                'name' => '5A Little Island',
                'management_company' => 'Site 500 Management CLG',
                'block_type_id' => 2,
                'user_id' => 4,
                'address1' => 'Euro Business Park',
                'address2' => 'Little Island',
                'address3' => 'Cork',
                'image_path' => null,
                'image_name' => null,
                'country_id' => 105,
                'state_id' => 1753,
                'car_spaces' => 0,
                'inspection_count' => 12,
                'no_of_units' => 16,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2023-03-25 12:05:37',
                'updated_at' => '2023-03-25 12:05:37',
            ],
            [
                'id' => 5,
                'name' => 'AnBruach',
                'management_company' => 'Halfway Management Company CLG',
                'block_type_id' => 1,
                'user_id' => 4,
                'address1' => 'Halfway',
                'address2' => 'Ballinhassig',
                'address3' => 'Cork',
                'image_path' => 'uploads/apm/block/photos/2023/03/',
                'image_name' => '1679754104.98_blockpicture_1515474021498.jpeg',
                'country_id' => 105,
                'state_id' => 1753,
                'car_spaces' => 0,
                'inspection_count' => 12,
                'no_of_units' => 59,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2023-03-25 12:07:39',
                'updated_at' => '2023-03-25 14:21:44',
            ],
            [
                'id' => 6,
                'name' => '14 South Mall',
                'management_company' => '14 South Mall',
                'block_type_id' => 2,
                'user_id' => 4,
                'address1' => '14 South Mall',
                'address2' => 'Cork',
                'address3' => null,
                'image_path' => 'uploads/apm/block/photos/2023/03/',
                'image_name' => '1679753896.109_blockpicture_1563249620701.jpeg',
                'country_id' => 105,
                'state_id' => 1753,
                'car_spaces' => 0,
                'inspection_count' => 12,
                'no_of_units' => 3,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2023-03-25 12:08:55',
                'updated_at' => '2023-03-25 14:18:16',
            ],
            [
                'id' => 7,
                'name' => 'Anglesea Street Management CLG',
                'management_company' => 'Anglesea Street Partnership',
                'block_type_id' => 2,
                'user_id' => 4,
                'address1' => '11 Anglesea Street',
                'address2' => 'Cork',
                'address3' => null,
                'image_path' => 'uploads/apm/block/photos/2023/03/',
                'image_name' => '1679754159.120_blockpicture_1535019959529.jpeg',
                'country_id' => 105,
                'state_id' => 1753,
                'car_spaces' => 0,
                'inspection_count' => 12,
                'no_of_units' => 5,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2023-03-25 12:10:28',
                'updated_at' => '2023-03-25 14:22:39',
            ],
            [
                'id' => 8,
                'name' => 'AnRadharc',
                'management_company' => 'An Radharc Maryborough Management Co CLG',
                'block_type_id' => 1,
                'user_id' => 9,
                'address1' => 'AnRadharc',
                'address2' => 'Maryborough Ridge',
                'address3' => 'Douglas, Cork',
                'image_path' => 'uploads/apm/block/photos/2023/03/',
                'image_name' => '1679754191.5_blockpicture_1491796821918.jpeg',
                'country_id' => 105,
                'state_id' => 1753,
                'car_spaces' => 52,
                'inspection_count' => 12,
                'no_of_units' => 52,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2023-03-25 12:13:17',
                'updated_at' => '2023-03-25 14:23:11',
            ],
            [
                'id' => 9,
                'name' => 'Ardghort',
                'management_company' => 'Ardghort Management CLG',
                'block_type_id' => 3,
                'user_id' => 9,
                'address1' => 'Highfield',
                'address2' => 'Ballincollig',
                'address3' => 'Co. Cork',
                'image_path' => 'uploads/apm/block/photos/2023/03/',
                'image_name' => '1679754220.66_blockpicture_1563249620702.jpeg',
                'country_id' => 105,
                'state_id' => 1753,
                'car_spaces' => 0,
                'inspection_count' => 12,
                'no_of_units' => 93,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2023-03-25 12:15:07',
                'updated_at' => '2023-03-25 14:23:40',
            ],
            [
                'id' => 10,
                'name' => 'Ard na Ri Banduff',
                'management_company' => 'Banduff Management Company CLG',
                'block_type_id' => 1,
                'user_id' => 6,
                'address1' => 'Ard na Ri',
                'address2' => 'Banduff Road',
                'address3' => 'Banduff, Cork',
                'image_path' => 'uploads/apm/block/photos/2023/03/',
                'image_name' => '1679754375.11_blockpicture_1494907201380.jpeg',
                'country_id' => 105,
                'state_id' => 1753,
                'car_spaces' => 0,
                'inspection_count' => 12,
                'no_of_units' => 16,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2023-03-25 12:16:39',
                'updated_at' => '2023-03-25 14:26:15',
            ],
            [
                'id' => 11,
                'name' => 'Ashmount Court',
                'management_company' => 'Silver Way Management Company Limited',
                'block_type_id' => 1,
                'user_id' => 6,
                'address1' => 'Ashmount Court',
                'address2' => 'Silversprings',
                'address3' => 'Co. Cork',
                'image_path' => null,
                'image_name' => null,
                'country_id' => 105,
                'state_id' => 1753,
                'car_spaces' => 0,
                'inspection_count' => 12,
                'no_of_units' => 33,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2023-03-25 12:22:53',
                'updated_at' => '2023-03-25 12:22:53',
            ],
            [
                'id' => 12,
                'name' => 'Baltimore Holiday Homes',
                'management_company' => 'Blatimore Holiday Homes Management CLG',
                'block_type_id' => 1,
                'user_id' => 1,
                'address1' => 'Baltimore',
                'address2' => 'Co. Cork',
                'address3' => null,
                'image_path' => 'uploads/apm/block/photos/2023/04/',
                'image_name' => '1680344022.Baltimore.jpeg',
                'country_id' => 105,
                'state_id' => 1753,
                'car_spaces' => 0,
                'inspection_count' => 12,
                'no_of_units' => 34,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2023-03-25 12:25:13',
                'updated_at' => '2023-04-01 10:13:42',
            ],
        ];

        foreach ($blocks as $block) {
            DB::table('blocks')->insert($block);
        }
    }
}
